services:
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
    - "8081:8080"
    volumes:
    - ./openapi:/openapi
    environment:
      SWAGGER_JSON: /openapi/spec.yaml

  postgres:
    image: postgres:15.10
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
      KC_RESPONSE_HEADERS_ALLOW_ORIGIN: "*"
      KC_RESPONSE_HEADERS_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      KC_RESPONSE_HEADERS_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,OPTIONS,DELETE,PUT"
      KC_RESPONSE_HEADERS_ACCESS_CONTROL_ALLOW_HEADERS: "Authorization,Content-Type"
      KC_RESPONSE_HEADERS_ACCESS_CONTROL_ALLOW_CREDENTIALS: "true"
    command: ["start-dev"]
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local